### ISSUE TITLE
Pathfinding sometimes broken

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#10]
No and then the pathfinding seems broken, thus some settlers walk far outside the land for reaching their destination.

As there are no replays, I don't know what other information I can give.

**Comment by nicymike** [comment]
I watched your video on youtube and I think you mean settlers running around all over the map.

There must be a problem if a settler is getting lost and not finding a way back to home. This happens if you burn a building or cut a road.

**Comment by nicymike** [comment]
This will be fixed in the next development version. There was indeed a bug in the pathfinding for lost settlers. They will now try to stay inside borders and find a way back to a stock or the castle from there. The pathfinding is now exactly as it is in the original game.
