### ISSUE TITLE
ARCHIV.DS — Lowercase letters is not shown in original game.

### ISSUE THREAD

**Issue by ShpakMA** [nicymike/serflings#107]
[archivDS.zip](https://github.com/nicymike/serflings/files/11687595/archivDS.zip)
 
Please convert all names of saves to uppercase during saving...
 
![ARCHIVE file lovercase names issue](https://github.com/nicymike/serflings/assets/134811226/063489ee-dd1d-4db4-9b53-e5e5c32d6583)

**Comment by nicymike** [comment]
Oh, I didn't check the names in the original game. Thank you for reporting.

**Comment by ShpakMA** [comment]
The password is shown by both Settlers and Serflings when save file is loaded. (good)
![Снимок экрана в 2023-06-09 01-18-11](https://github.com/nicymike/serflings/assets/134811226/831e53fc-6370-4935-a65e-74c93bdc1c02)

 
The password still shown by both Settlers and Serflings when loaded game is aborted. (good)
![Снимок экрана в 2023-06-09 01-18-32](https://github.com/nicymike/serflings/assets/134811226/5080612e-8bde-4cc3-8df7-6dd03ee85427)

 
The **password from first level** is shown by Serflings if level is switching by arrows after aborted load. Settlers do same, but show **password from loaded level** always. Not from selected. (bug)
![Снимок экрана в 2023-06-09 01-19-10](https://github.com/nicymike/serflings/assets/134811226/1eee70fb-7829-4d50-9e90-4f27a6b555cb)

**Comment by nicymike** [comment]
Please don't mix issues because I fixed the first one (uppercase names) in recent snapshot and I need more time to check the second one (password).

**Comment by ShpakMA** [comment]
> Please don't mix issues because I fixed the first one (uppercase names) in recent snapshot and I need more time to check the second one (password).

I am sorry. Should I open new Issue?

**Comment by nicymike** [comment]
> I am sorry. Should I open new Issue?

Yes. It is better because I can shedule separate issues for different versions.

**Comment by nicymike** [comment]
I will close this issue because the fist error is fixed in latest snapshot. The second error has been moved to #109.
