### ISSUE TITLE
Buildings not always built after reconnecting roads

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#11]
As the title says, it's sometimes possible, that a building is not continued building when the road to it is disconnected.

**Comment by nicymike** [comment]
Must be a bug in resource scheduling.

**Comment by nicymike** [comment]
I think this has been finally fixed in the next development version by rewriting the code for building processing. The new code is working exactly the same as the original game.
If I am wrong please open again or create a new issue.
