### ISSUE TITLE
Automated path builder, always finds the most efficient route between 2 points!

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#110]
This is a great tool you implemented. But if I am not mistaken, it is working even too well, by finding always the most efficient route between 2 points instead of the shortest, That takes a bit away the last self thinking process, so there is hardly nothing left to do, to enhance any routes by oneself. Maybe could add an option between the 2 choices?

**Comment by nicymike** [comment]
Good point. I like your idea. Adding an option should not be too hard.

In the current version the average walking speed is considered while calculating the best path. If I remove this value from the calculation, the shortest path will be used.

**Comment by nicymike** [comment]
I added a setting in the newest snapshot which allows to set the calculation either to short or to fast.
