### ISSUE TITLE
Production chart background not fitting chart

### ISSUE THREAD

**Issue by notarocketscientist** [nicymike/serflings#113]
Hi!

I noticed today, that the background of the production chart is a bit "off" (on the right and bottom axis).

See details and image here: https://github.com/notarocketscientist/serflings-debug/tree/master/production-chart-background

**Comment by nicymike** [comment]
Oops! How could I not see this while reworking the window (#45). Thank you for the hint. :)

**Comment by notarocketscientist** [comment]
Sometimes you just need a couple of additional eyes - especially when working on a project for a long time.

**Comment by nicymike** [comment]
Fixed in next Snapshot
