### ISSUE TITLE
[Feature] Set same wares in MP

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#12]
It'd be really nice to have an easy way to set the same resources for every player in multiplayer. So far not of my tries were working setting the same resources.

**Comment by nicymike** [comment]
This is on my list.

What you could do for now:
Create a new game for two players for example with the history edition and set all bars to maximum. Then start and save the game and load it in serflings multiplayer.

**Comment by nicymike** [comment]
When creating a network game, the values for stock and growth rate are now set statically until there is an option to change it.
