### ISSUE TITLE
Soldiers getting stuck

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#13]
When burning a military building after the last soldiers died, all attackers seem to get stuck. 

![image](https://user-images.githubusercontent.com/1276342/74101321-c8f56a80-4b38-11ea-8957-a18bf546e359.png)

**Comment by nicymike** [comment]
In the original game your are not allowed to burn a building that is currently beeing attacked.

**Comment by nicymike** [comment]
The demolish will be denied in the future if the building is currently beeing attacked.
