### ISSUE TITLE
Localize buildings

### ISSUE THREAD

**Issue by rtrzebinski** [nicymike/serflings#130]
In the menu where buildings ready/requested are displayed - click on the building to select it on the map (same way as notifications are selecting a place).
Case - I planned multiple mines, never connected them with a road, so they are waiting for the time when needed. Now I need a gold mine, but where is it?

**Comment by Darmorque** [comment]
• Open map
• Special-Click on the building icon beneath the map
• Select desired building
• Voila! Only this type of building is shown on the map.

**Comment by rtrzebinski** [comment]
@Darmorque Is it the proposal or a feature I'm not aware of? :)

edit: I see it is a thing, nice, thank you!

https://github.com/nicymike/serflings/wiki/Misc#localize-buildings

**Comment by Darmorque** [comment]
Yes, it's a game feature apparently, and the one that I wasn't aware of for 30 years. ;) I discovered that just recently by thorough re-reading the manual. :D
