### ISSUE TITLE
Buildings not fully occupied

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#16]
Possibly after an attack

![image](https://user-images.githubusercontent.com/1276342/84406113-5d67fa80-ac09-11ea-9efc-b29429dd6af4.png)

![image](https://user-images.githubusercontent.com/1276342/84406144-6a84e980-ac09-11ea-81c3-ec07a04e4f85.png)

**Comment by nicymike** [comment]
Do you have enough knights available? Is this building still not occupied after some time of waiting?

**Comment by Spikeone** [comment]
@nicymike if by knights any soldier is accounted, then yes. If by knights only a specific rank is accounted, then no.

**Comment by nicymike** [comment]
The buildings should be occupied by any rank so this might be a bug.

**Comment by Wakeboardtiger** [comment]
I noticed that this happens the second time after you pressed the knights swap button. 
![image](https://user-images.githubusercontent.com/68932712/96228483-d7492f80-0fbf-11eb-964f-0743987b750f.png)
![image](https://user-images.githubusercontent.com/68932712/96228504-ddd7a700-0fbf-11eb-81db-2b520b30ae94.png)
![image](https://user-images.githubusercontent.com/68932712/96228582-f647c180-0fbf-11eb-84b8-dc7f6979422c.png)
[SAVE5.zip](https://github.com/nicymike/serflings/files/5390058/SAVE5.zip)

**Comment by nicymike** [comment]
I also realised that knight exchange is sometimes stuck at sending out knights. If you click again on exchange there is a chance that it will fix itself.

**Comment by nicymike** [comment]
Knight exchange will be fixed in next development version.

**Comment by nicymike** [comment]
I think this has been finally fixed in the next development version by rewriting the code for building processing, although I did not find a bug in the old code.
If I am wrong please open again or create a new issue.

**Comment by nicymike** [comment]
I think this has been finally fixed in the next development version by rewriting the code for building processing, although I did not find a bug in the old code. The new code is working exactly the same as the original game.

If I am wrong please open again or create a new issue.
