### ISSUE TITLE
Screenshot shortcut

### ISSUE THREAD

**Issue by Richard-L** [nicymike/serflings#18]
Please can you add a keyboard shortcut for screenshot taking. This is something often used for bug reporting or otherwise illustration. 

Bonus: add a shortcut for video recording.

Please can images/video be saved in a "capture" or "screenshots" folder of the client's location?

Many thanks in advance.

**Comment by nicymike** [comment]
Screenshot is possible but I don't think I can add video recording. You better use an external program to handle this.

One question:
What do you mean by "folder of the client's location"? Some default folder of the operating system or a subfolder of where you executed Serflings?

**Comment by Richard-L** [comment]
Thank you!

And from where the executable lies. Please no usage of %userprofile% on Windows if possible.

**Comment by Richard-L** [comment]
Returning to this: while it's possible to use the PRINT screen for capture, this usually means any scaling and respective pixel-blending is also captured. We would need a screenshot function that captures the pure 1:1 output (ie frame buffer).

**Comment by nicymike** [comment]
I think I will add this to the next version and I think I will map it to the PRINT key, too.

**Comment by nicymike** [comment]
The screenshot possibility is finished an already included in the newest development version.
