### ISSUE TITLE
Stock will sometimes get stuck (bug from original game)

### ISSUE THREAD

**Issue by nicymike** [nicymike/serflings#23]
Somethimes stocks will get stuck an no longer move stuff out.

See:
https://github.com/nicymike/serflings/issues/20#issuecomment-666542134

Save (just remove ending ZIP): [SAVE3.DS.ZIP](https://github.com/nicymike/serflings/files/5002393/SAVE3.DS.ZIP)
The warehouse to the north east of the main castle is stuck.

**Comment by nicymike** [comment]
I checked the stock and it is stuck because the state of the building is invalid. Did you create this savegame in the original game or inside Serflings?
I did not find an issue which could create such an invalid state but maybe it is because of an older bug in Serflings which is now fixed.

/cc @Wakeboardtiger

**Comment by Wakeboardtiger** [comment]
I think i used the original game.

**Comment by nicymike** [comment]
Even knowing the original code I don't know how this can happen. I guess I need to dig deeper into it.

The invalid state is:
The stock counts settlers which want to go out. If this count is above zero the carrier will not carry stuff out because he will always wait for the settlers to go out first.
The stock in question has a counter of one but no settler which want to go out. This will freeze the carrier forever.

**Comment by nicymike** [comment]
I did not find the cause but I did some optimizations about stock control. If a stock is stuck because of a wrong outgoing queue for settlers, it will be fixed while loading a game. This also fixes your savegame.

Because you provided a savegame from the original game the bug may not exist in Serflings.

Feel free to reopen or create a new issue if you come accross the bug again in Serflings.
