### ISSUE TITLE
Option in Multiplayer to work in the same team.

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#25]
As in the original game, is it possible to play together the blue guys in a mission or created single player game? 
See the option on the picture below from the original game, where i can choose two mice for one player.
![image](https://user-images.githubusercontent.com/68932712/89092440-0f3ad080-d3dc-11ea-97c3-373a43b15923.png)

As with the option of creating game settings in here: https://github.com/nicymike/serflings/issues/12#issuecomment-584137797 
2 People on one player i could not manage to load, yet.

**Comment by nicymike** [comment]
This is currently not implemented but I will definitely add this. I even think of two players with blue fighting against two players with red.
To get this to work I have to do some internal changes to multiplayer first.

**Comment by Wakeboardtiger** [comment]
Sounds great. Thank you

**Comment by Wakeboardtiger** [comment]
Hello, any development here already?

**Comment by nicymike** [comment]
Actually I added this as a hidden feature in version 1.1.0 (team game).

Just do as follows:
1. Start a singleplayer game of your choice (trainings and missions are also allowed)
2. Save the game
3. Create a new network game
4. Load the game you saved in the previous step (Serflings will show a text if it detects a coop game)
5. Start the network game
6. Let the second player connect
7. Enjoy a team (coop) game

![image](https://github.com/nicymike/serflings/assets/19415000/7917aa3c-badc-4250-8956-5618430f35a2)

/cc @Wakeboardtiger

**Comment by Wakeboardtiger** [comment]
Good to know. ;)
Many thanks.
