### ISSUE TITLE
CRASH at MP network game Map size 8

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#26]
java.lang.OutOfMemoryError: Java heap space
	at net.simpleguide.a.a.c.b.a.<init>(net.simpleguide.Main:47)
	at net.simpleguide.game.serflings.j.a.d.a(net.simpleguide.Main:50266)
	at net.simpleguide.game.serflings.n.a(net.simpleguide.Main:531)
	at net.simpleguide.a.a.a.run(net.simpleguide.Main:1314)
	at java.lang.Thread.run(Unknown Source)

Only got this at biggest map size, but already a few times, always soon after starting the multiplayer game.

**Comment by Wakeboardtiger** [comment]
now start again all fine....

**Comment by nicymike** [comment]
Which package (download) of Serflings do you use?

**Comment by Wakeboardtiger** [comment]
0.24.0-SNAPSHOT 64bit

**Comment by nicymike** [comment]
How much RAM do you have installed?

**Comment by Wakeboardtiger** [comment]
36GB

**Comment by nicymike** [comment]
The main problem is the default maximum memory of 1GB Java is taking, which I did not change yet.
Can you send me the random numbers seen in the main menu or a savegame where the game crashes? I did some tests with map size 8 but the game runs very well without crashing.

Before I want to care about memory settings I want to switch from Java 8 to 11. I guess I should plan this for one of the next versions.

**Comment by nicymike** [comment]
I increased the maximum memory for the exe in the next development version. Can you verify if this fixes your crashes?
