### ISSUE TITLE
Mouse Lag in Fullscreen Mode

### ISSUE THREAD

**Issue by Richard-L** [nicymike/serflings#27]
As we'd discussed, and just to collect: there's sadly a mouse lag in fullscreen mode. Curiously, the lag is absent whilst in windowed mode.

**Comment by nicymike** [comment]
Already working on this.

**Comment by nicymike** [comment]
Will be fixed in next development version.

**Comment by Richard-L** [comment]
Confirmed working in v0.25.0 :+1:
