### ISSUE TITLE
Small bugs in the statistic and map pages

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#36]
Statistic shows only half of the correct value and only in one color:
![image](https://user-images.githubusercontent.com/68932712/95785840-b7381880-0d00-11eb-88fe-191eec614689.png)
![image](https://user-images.githubusercontent.com/68932712/95785994-fe260e00-0d00-11eb-845e-47b3813e3f1f.png)

**Comment by Wakeboardtiger** [comment]
Also on the enemies page a small difference:
![image](https://user-images.githubusercontent.com/68932712/95786212-56f5a680-0d01-11eb-91c0-4c7599abfb35.png)

**Comment by Wakeboardtiger** [comment]
House pages hides one digit if there are houses still in construction:
![image](https://user-images.githubusercontent.com/68932712/95786623-295d2d00-0d02-11eb-9310-314fabda55e5.png)

**Comment by Wakeboardtiger** [comment]
People page misses number of unemployed:
![image](https://user-images.githubusercontent.com/68932712/95786998-d6d04080-0d02-11eb-925c-33d733aaca5f.png)

**Comment by Wakeboardtiger** [comment]
Map cannot show dithered mode:
![image](https://user-images.githubusercontent.com/68932712/95787314-78579200-0d03-11eb-9d41-2169373aec61.png)

**Comment by Wakeboardtiger** [comment]
Attack menu misses black background on the numbers:
![image](https://user-images.githubusercontent.com/68932712/95787903-a4274780-0d04-11eb-9324-de24907ce9bf.png)

**Comment by Wakeboardtiger** [comment]
And many thanks for the great work and nice enhancements in the latest release, Nicymike.

**Comment by nicymike** [comment]
Thank you for the tests but please stay at creating single tickets for issues which are not related. I cannot handle different version inside a single ticket.
