### ISSUE TITLE
No exchange of knights inside the main castle

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#40]
I noticed that in the original game, there is a constant exchange happening in the main castle between the knights who are remained back as defense and the ones which are stored in there. If you call people back to defense, therfore increasing the number up to 99, the best knights will be called to stay for defense, same as in serflings. But then in the original, the good knights getting slowly released again and swapped with newbies, not in serflings, so. But this has the advantage that if I want to swap knights with the outside forts, that the good ones are waiting, ready to be exchanged, not the newbies.
Maybe this feature in serflings is missing, since there is still this delay missing, of calling or dismissing knights. Looks like there is a special mechanism behind this, which is organizing all this and creates therefore a delay.

**Comment by nicymike** [comment]
Serflings actually did a swap but in reverse. This will be fixed in the next development version.
