### ISSUE TITLE
Courser does not show type of building area

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#41]
As can be seen on the picture, courser does not show the available building area on the building in serflings. This can be useful if you in need to find a big building spot.
![image](https://user-images.githubusercontent.com/68932712/95862859-af728580-0d8d-11eb-9c89-0199165ae8c3.png)

**Comment by nicymike** [comment]
You are right, this is currently not implemented.

**Comment by Wakeboardtiger** [comment]
this is especially necessary, for games with limited space, aka map size 1 or 2

**Comment by nicymike** [comment]
I just added this. Just check out the new version on the website.

Replacing a building is a different issue and is more complicated.
