### ISSUE TITLE
Main castle easier to fight in original game

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#44]
Looks like, the fight against the AI in the original game does not require to fight all Knights left in the castle. Suddenly the castle burns and the knights are all lost. In serflings, one has to fight everybody, which is not a problem at 8x speed
[SAVE5.zip](https://github.com/nicymike/serflings/files/5374193/SAVE5.zip)

**Comment by nicymike** [comment]
I need to check this because I thought you will always fight all knights in the original game.

**Comment by nicymike** [comment]
Please test with newest version. The logic for the castle is now the same as for the original game so the fight should also be the same.
If still not: Do you have a comparison with the original (maybe number of knights)?

**Comment by Wakeboardtiger** [comment]
I think its working now. Probably had to do with the numbers of Knights you leave behind to defend. AI might set the number too low so you win quick, destroying the castle with the rest of the knights left in the stock. Since in earlier versions of serflings knights where instantly added to defend the castle as it was described here: 
https://github.com/nicymike/serflings/issues/20#issuecomment-666542134

You always had to fight all knights left in the stock since it was instantly added to the castle again.

**Comment by nicymike** [comment]
Yes, the knight exchange has been changed to match the original game. Feel free to close this issue if you think it is fixed now.
