### ISSUE TITLE
Call of Geologists closes window even if no Geologist can be called. 

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#51]
In the original game, calling a Geologist keeps the info page open, if Geologist cannot be called to this position, due to no road connection or no more available Geologists. In serflings it is still closing. One can hear the negative sound, so.
![image](https://user-images.githubusercontent.com/68932712/96073527-d1c0ec00-0ed0-11eb-80b3-44b0ab614452.png)

**Comment by nicymike** [comment]
That is because I split up the dialog and the actual sending to support multiplayer. The game returns success or failure only after the actual sending. To fix this I have to add a function to simulate sending.

**Comment by nicymike** [comment]
Fixed in 1.1.0
