### ISSUE TITLE
Goods traffic jams on flags are not getting solved sufficiently 

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#52]
I think there is a problem as soon as a flag has too many goods in serflings. I noticed that the carriers sometimes will walk to the flag with an item and walk exactly with the same item back again. That leads to no solution of the problem at that flag. I think in the original game it is rule that they have to take a different item from the flag, so the traffic flow doesn't come to a halt. 
Also I noticed that the goods will not take another direction. For example: one overloaded flag, 3 roads. The goods only carried by two roads forth and back. The third guy doesnt interact at all and on his end of the road there is an empty flag. I read something on the manual that on overloaded roads, goods will find a different way. Did not see that happening in serflings yet.
But there might be other differences as well. For now I just noticed that goods jams getting solved way better in the original game.

**Comment by nicymike** [comment]
You are right. In the original game, a different path will be used when a flag is jamed. This feature is still missing in Serflings.

**Comment by Wakeboardtiger** [comment]
The jams are really not nice. They stall the game very quickly and also the AI opponents, I think. Like the yellow one in this game here. Funnily the violet one just came back a live and starting now after 10hours. :)
[SAVE6.zip](https://github.com/nicymike/serflings/files/5394743/SAVE6.zip)

**Comment by nicymike** [comment]
The traffic jams for goods have been fixed in the latest development version. I also verified that the flag processing for goods is now exactly as it is in the original game.
