### ISSUE TITLE
 building options does not update or yellow courser can still be moved while building page open

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#58]
The yellow courser still can be replaced after opening the building page in order to choose the house which should be build at that courser place. But if the yellow courser is moved to a different location, while the building page is still open, with different house option ( mine or castle ) the building page doesn't update and no building can be chosen to be build. I think in the original the yellow courser is frozen and cannot be moved after the building page is opened.

**Comment by nicymike** [comment]
This is fixed in the newest snapshot version. The game will close the window if you change the cursor. Can you validate this with newest 1.0.0-SNAPSHOT?

I don't like the freeze so I decided to close the window instead.

**Comment by Wakeboardtiger** [comment]
yeah probably still used a old version, sorry

**Comment by nicymike** [comment]
No worries, I did many bugfixes today and updated the version a lot.
