### ISSUE TITLE
Incorrect fullscreen screenshot resolution

### ISSUE THREAD

**Issue by Richard-L** [nicymike/serflings#59]
Dear Mike,

as I'm finding this again in the new v1.0 final, I notice I hadn't created this issue yet.

When using the PRINT key to take a screenshot, the output is correct only in windowed mode. If you play in fullscreen, the screenshot assumes the same resolution you would have in windowed mode, but seem to compress the added pixels into it:

Windowed mode screenshot:
![serflings-2021-06-19_17-43-41](https://user-images.githubusercontent.com/4934209/122647803-4914e280-d126-11eb-9ebc-908797269dd6.png)

Fullscreen mode screenshot:
![serflings-2021-06-19_17-43-29](https://user-images.githubusercontent.com/4934209/122647810-50d48700-d126-11eb-8654-72af7a10697a.png)

My fullscreen resolution is 1920x1200px.

Many thanks for looking into this, and congrats on the progress with this project !!!

**Comment by nicymike** [comment]
Will be fixed in a bugfix I plan to release this week
