### ISSUE TITLE
[Issue] Stock window wrongly drawn

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#6]
![image](https://user-images.githubusercontent.com/1276342/71738434-e444ca00-2e56-11ea-84d2-cb393bc71f84.png)

![image](https://user-images.githubusercontent.com/1276342/71738439-e6a72400-2e56-11ea-9033-06422261ba95.png)

**Comment by nicymike** [comment]
Fixed in next version. There was something wrong with knight calculation after a battle.
