### ISSUE TITLE
another "Back-to-Desktop"

### ISSUE THREAD

**Issue by AX-Turbo** [nicymike/serflings#62]
after instantly re-attacking one of the knights
 huts which the computer opponent  has just conquered from me.
 
 ![error-message](https://user-images.githubusercontent.com/16238956/123991321-e85d9380-d9ca-11eb-94b4-2f8e90ca002e.png)

**Comment by nicymike** [comment]
The error is regarding a window that has been closed. Do you remember anything about that?

**Comment by AX-Turbo** [comment]
my last action before the BtD was, setting the amount of knights at the "attack" window and klicking on the "crossed swords" bottom-left.

**Comment by nicymike** [comment]
I guess I have an idea to fix this. I'll try work on this next week.

**Comment by nicymike** [comment]
Fixed in next snapshot
