### ISSUE TITLE
game crashes on linux when sound is enabled (while music works)

### ISSUE THREAD

**Issue by icetmatt** [nicymike/serflings#63]
When I enable sounds the game immediately crashes when I start a game. It works when I just have music enabled, but when sound is enabled i receive this:

```
java -jar serflings-1.1.0-SNAPSHOT.jar 
java: /build/openjdk-8-RKFhH1/openjdk-8-8u292-b10/icedtea-sound/src/native/org_classpath_icedtea_pulseaudio_Stream.c:729: Java_org_classpath_icedtea_pulseaudio_Stream_native_1pa_1stream_1cork: Assertion `operation' failed.
Aborted (core dumped)
```

I am running an Ubuntu flavor:
```
Linux tomslaptop 4.15.0-118-generic #119~16.04.1-Ubuntu SMP Tue Sep 8 14:54:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

What information would you need to track down this issue?

Pls let me know, I would love to have sound and enjoy this game I am still enjoying on dosbox. :)

Fantastic Job, thanks!

**Comment by icetmatt** [comment]
After some research I noticed that there are at least two java runtimes, _openjdk_ and the _oracle_ one. I also installed the oracle runtime et voilà, no more sound issues.

Long story short: This is rather a java bug, not an issue with the game.

Feel free to close/archive this bug report. Might be helpful for others which struggle with similiar issues.

**Comment by nicymike** [comment]
Thank you for the research. This bug remembers me of a similar bug on raspberry pi: https://github.com/nicymike/serflings/issues/57

I plan to migrate the game to Java 11 (OpenJDK). I guess this will improve the support for openjdk in general.
