### ISSUE TITLE
Lumberjack has a radius of 7 steps, not only 5

### ISSUE THREAD

**Issue by DerKeil** [nicymike/serflings#68]
Hey,

I realized that Lumberjacks (in Version 1.0.2) only walk up to 5 steps to reach a tree, but in the original game it is up to 7 steps.

(I did not check whether Forest Rangers behave correctly.)

Thanks
Stefan

**Comment by nicymike** [comment]
I checked the code and did some tests but I don't see any differences. The area is the same in DOS and Serflings. How did you test this?

Save before cutting down the trees: [SAVE1.zip](https://github.com/nicymike/serflings/files/7899329/SAVE1.zip)

Serflings:
![image](https://user-images.githubusercontent.com/19415000/150184677-99141ef5-22cc-4829-b703-a2b86c303d8c.png)

DOS:
![image](https://user-images.githubusercontent.com/19415000/150184725-82bb65a9-3ffa-4271-bfb5-e3f50bb9ad7b.png)

History Edition:
![image](https://user-images.githubusercontent.com/19415000/150184769-caa84be1-6e1a-43e4-bfa6-87e3072a7fa3.png)

**Comment by DerKeil** [comment]
Hey Nicymike,

thanks for checking this and sorry for wasting your time. I was playing Serflings for a while and had the impressions that the trees which are more than 5 steps away from the flags are not removed. But obviously I was wrong. Further, I just realized that radius is not 7, it is 6, but counted from the building and not from the flag.

So many learnings after so many years :)

Best
Stefan

**Comment by nicymike** [comment]
No worries. I am happy to see people comparing Serflings with the original game to find differences.
