### ISSUE TITLE
Can demolish military builings that are already under attack

### ISSUE THREAD

**Issue by DerKeil** [nicymike/serflings#71]
Hey,

I am pretty sure that in the original game it was not possible to demolish a military building that was already under attack, but in a 2 human player game it was (sometimes) possible.

Best
Stefan

**Comment by nicymike** [comment]
The behaviour should be the same because I did check it some versions ago.

It works like:
If there is an enemy knight in the area around the building, forbid demolish. It doesn't matter if there was an attack recently.

I will check the radius to be sure

**Comment by DerKeil** [comment]
Oh really, it depends on whether the attacking knights are already near the builing. hmmm, didnt know. Thanks

**Comment by nicymike** [comment]
I got this information from the original code.
This will also block demolish for buildings near the border if an enemy knight is walking on a path on the other side of the border.

**Comment by nicymike** [comment]
Is this still an issue?

**Comment by DerKeil** [comment]
No, you already explained the reason.
