### ISSUE TITLE
(Cosmetic) Trees grow on water

### ISSUE THREAD

**Issue by juj** [nicymike/serflings#74]
Some palm trees appear on top of water:

![image](https://user-images.githubusercontent.com/225351/179707920-3a32b69c-795c-47a5-ad46-fd4de1a13f02.png)

**Comment by nicymike** [comment]
Yes, that is intended. It is a water tree that also exists in the original game (DOS).

![image](https://user-images.githubusercontent.com/19415000/179716396-b935c581-c9be-4a2b-963d-b84583fb6b4e.png)

**Comment by juj** [comment]
Ohhh! Sorry for the noise, and thanks for the quick turnaround :)

**Comment by nicymike** [comment]
No worries. :)
