### ISSUE TITLE
AI may be left with undefeatable mines

### ISSUE THREAD

**Issue by juj** [nicymike/serflings#76]
After destroying all buildings from an enemy, it is possible that they will be left with some mines that don't have any kind of guard structure, but the area does not disappear either from the enemy's control: (enemy is pink here, players is blue)

![image](https://user-images.githubusercontent.com/225351/179852540-ca3a0016-ee1f-4a23-b430-9c48e7825be5.png)

**Comment by juj** [comment]
Uhh, sorry, I am super blind.. there IS a guard structure, but it is just behind the rightmost mine.. (lol :) )

**Comment by nicymike** [comment]
Yes, hard to see. 😀
