### ISSUE TITLE
First player goal always already achieved without even being on the map yet.

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#87]
I noticed that without having build anything, I always achieve the first goal right away with the other cpu players arriving in the game. Is that supposed to be like this?
![image](https://user-images.githubusercontent.com/68932712/219800064-5943d927-c136-4357-8219-195c5bb2560c.png)

**Comment by nicymike** [comment]
Yes, this is intended and this is how the original game works. The first goal is to reach a global score for buildings of 50. A castle has a score of 20 so three castles will already fulfill the goal.
The only purpose of this is to prevent the first player which placed the castle beeing the winner. If no other player is on the map yet, the first player will have a map ownership of 100% and a military score of 100%.

**Comment by Wakeboardtiger** [comment]
Thanks for explaining, Nicymike.
