### ISSUE TITLE
On the 2.0 snapshot releases in mission 13 some roads can not be build

### ISSUE THREAD

**Issue by stepo2** [nicymike/serflings#90]
SNAPSHOT release 2.0 (all so far as far as I could test).
Mission 13

Trying to expand the town to the northwest is not possible because it is not possible to connect roads at some point. Specifically the area between the lake and the mountain.

Direct after start build a flag to the very far north west in the starting territory and try to bild a road: most paths are not buildable, even thoug hthe land is free and the build icon is there. Even trying to use as many flags as possible is not possible.

Not sure if this happens in other missions as well, discovered it on mission 13.

**Comment by stepo2** [comment]
Update: in preview mode it works! With both automatically and manually built roads. Only in standard mode the bug is there.

**Comment by nicymike** [comment]
Do you mean clicking on the icons for path building does nothing? Actually the icons are not clickable at all but the game checks the map location where you did click to build the path. This is especially hard if the land is steep.

This is the same in the original game. Just try to find the right spot. Please test if this works in standard mode.
I plan to change this in the future.

**Comment by stepo2** [comment]
The following screen is from mission 13, Snapshot-release, without preview mode. I can not build any roads down. I zoomed in and literally clicked every pixel around the place (on and off steepness "buttons", near and far away).

![no_path_possible](https://user-images.githubusercontent.com/127047691/226572909-c37a9717-ce5c-4b74-81da-0f3e1676c7b4.png)

**Comment by nicymike** [comment]
Interesting. I will check this.

**Comment by nicymike** [comment]
Fixed in newest snapshot. I accidentally introduced a bug while adding the feature for auto building of paths.

Thank you for the hint.
