### ISSUE TITLE
Feature suggestion: auto-building of flags for easy road-joining

### ISSUE THREAD

**Issue by stepo2** [nicymike/serflings#91]
Situation: have a long road without flags. Built a new road crossing the old one. Oh no, no flag is there: build a flag, then restart the whole new road-built-process again.

It would be nice if the road-built tool could auto-build flags if building a road onto an existing road at a point where a flag would be possible and needed.

**Comment by nicymike** [comment]
This is already included in the game.
If special click additional is enabled, you need to press special click to connect a new path with an existing one and building a flag at the same time. It works the same in the original game.

If you disable it, there will be a flag icon which indicates that you may click to connect the path.

![image](https://user-images.githubusercontent.com/19415000/226551829-697a8c1f-9640-420e-94b9-8ea42f1cd893.png)

![image](https://user-images.githubusercontent.com/19415000/226552217-ba17b374-241f-452d-8907-038b818c6df9.png)

**Comment by stepo2** [comment]
Ah, thank you. :) Was always wondering what this option actually means. Deactivating this is the better option here then.

If this is possible maybe a better label should be used, so that one knows that the option is about road/flag building (and not just generally about some mysterious click).

**Comment by nicymike** [comment]
The option disables some additional parts where you need to use the special key in the original game: demolish, stock management and road connection

If tooltips are added somewhere in the future this will be clear. :)

**Comment by nicymike** [comment]
I added more text to the options. Should be easier to understand now.

I will close this issue due to already implemented.
