### ISSUE TITLE
Feature: allow destroying flags at road ends while destroying the dead road end implicitly

### ISSUE THREAD

**Issue by stepo2** [nicymike/serflings#92]
Possible current example situations:
* have a flag only for geologist: when he's done you have to first clear the road, then the flag
* have an empty mine at a "dead end": after destroying the mine, you have to destroy the road first, then the flag

Proposal:
Allow that flags at road ends can be destroyed while implicitly destroyng the road as well.
Maybe via option toggle, but personally I would not mind having it always on.

**Comment by nicymike** [comment]
Duplicate of #30

**Comment by nicymike** [comment]
This is also on my private list

**Comment by stepo2** [comment]
Ah, didn't see the otehr issue. I'll close this one here then.
