### ISSUE TITLE
Feature (or original bug fix?): allow stonecutters to also cut behind buildings/other "obstacles"

### ISSUE THREAD

**Issue by stepo2** [nicymike/serflings#94]
Currently a stonecutter ignores rocks behind buildings (maybe in other situations as well) even if it is fully in his range.

While such a behaviour is understandable for woodcutters (where a tree could fall on the house) it is extremly annoying and does not make any sense for stonecutters that don't need free space aroudn their work place.

I always wondered back then whether this even is an original game bug.

**Comment by stepo2** [comment]
Sorry, duplicate of #24 .

**Comment by nicymike** [comment]
Yes, has already been discussed. I am not sure whether it is a bug or a feature but I think it was made because of animations.

**Comment by stepo2** [comment]
Yes, that's also my assumption. Maybe introducing "mirrored" animation would solves this (also for trees that otherwise would fall on buildings): if a node is visually blocked, just mirror the animation so that it looks correct.

On non-blocked nodes this mirroring could also happen randomly. This would add some nice graphical variation wthout changing the actual gameplay. Sometimes the woodcutter let the tree fall to the right, smometimes to the left.

**Comment by nicymike** [comment]
I don't know how to change animations yet because I ported most of the stuff directly from the original assembler without understanding how it works. But I am currently trying to catch up. :)
